# set port
server:
  port: 9090

# build database connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?serverTimeZone=GMT%2b8
    username: root
    password: 15853198730CQC

#mybatis:
#  mapper-locations: classpath:mapper/*.xml # redirect the path of xml mapper

# open sql log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl