# set port
server:
  port: 9090
  ssl:
    key-store: classpath:9279984_www.datezbackend.cn.jks
    key-store-password: 9rmmj18f
    key-store-type: JKS
# build database connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?serverTimeZone=GMT%2b8
    username: root
    password: 15853198730CQC
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

#mybatis:
#  mapper-locations: classpath:mapper/*.xml # redirect the path of xml mapper

# open sql log
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


file:
  upload:
#    path: E:\appointment\files\
    path: /home/files/
  download:
#    path: http://localhost:9090/file/download/
    path: https://www.datezbackend.cn:9090/file/download/
