# set port
server:
  port: 9090

# build database connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?serverTimeZone=GMT%2b8
    username: root
    password: 15853198730CQC
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

#mybatis:
#  mapper-locations: classpath:mapper/*.xml # redirect the path of xml mapper

# open sql log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


